language: java
jdk: oraclejdk8
#script: bash ./deploy.sh
script: "mvn deploy --settings settings.xml"
env:
  global:
  #- ENCRYPTION_LABEL: "09727d2d1f11"
  #- COMMIT_AUTHOR_EMAIL: "jan.hof99@gmail.com"
  - secure: "VQtpqABqzr5IiduVDWljPPh5pDwOAR2YESEmlFszOmJ8J9yEcPt9jg4xwCPgVESG+N0vAmoHumdjXpBp9Pr9ZsBm+44Ab6Jvf62DcVBEboUHb21pqR5KvAJEjrwMmkSNvNd+QEVCGX0zVgIRXwbkw/IiK4WDoRP+PWhwcaI9GDYsZplJ43FG4GFFmqh6hNtsm2WJswf0kVv78OsNu/2/5SjjJjyX2Jb9c//Of687lEnfYcXSTLBYPQHCIe5AO+GvJy/ge6fwC7nz+6ozgB6aCZRFyEFDlLCpeY+7r6fJO8GK5BtZWwtlINNx18igLt0kB2vJco1GngUmubYmR65X8/9qtZwV74WY4tA39m41O08Nr3J23SRGsd+2uTRYL5oM8HeE6cprXr3RPbfcfHZdfWrSPtRP2q0+x80y89M6vCZLNfGqEP5X5DUPkHSyuJNbTFFdf8TBCuvJV+F28adW+BV0jWLZeencO48EDtuJNcpamrXSa6llVCjV5YEJkHmGe8QXS8lf8TU6A4CXIcTFIzTEt4CR137oZUKRnn6JmO4PaRsBPP9zypd+L3/YJsTTumNoSQHope6UINjMZYSkh2wPNBDvidWS4+5ZkMdwvUjVE68TruYZZfQ7F7mUfjGr4gZcIhsKvgBl2p+EiNNKO7h0KbAjVSsrvsl7LdDi/vM="
  - secure: "acuQvfB52DCdHGBzkQUzCDkm9km+V+R3cwNiSMayCTWkwcrIhJ0f8ogdACCu7ZGxJ6rdI2WhZUMmtQHbh2BRRtVHf8cKFDW+le1GzzGjzpxknL5kkwLy1JYgFonLTqu8Kw8linXULQJhLSopcTZDhq2Rr/zFCNMFXJ+CaA/np3yBLxPx22UUboJ3eOHtDE+ByHGEfVJyKOQeTbbmo4o86DX6ZFDSRFK2sJitTTNDwy8R6C/BExu9fM8XqpBFD1XK4Y754Ev5V1Qhk2ccbRI3GjFD+Rh8E4tExZCCZoLZGIyVdWgGniIPBF2lQK7kPOu+kM+JROgBWtdZg1OJloYXQZvciEwc1aoTole3yGQAWCt2kaKrAHQtG6Su2VMoFKdRZJNdL4klM8o0/GXB+oQm+QN1JiLD+fC3yxUB3a318AgXF5gJKCrBhFSsm95121bBYdYmvP9pY5tgbOW/cPo1ZulMkguRdFjUGl6f1hg0FsuB05amxDBV+I7uExIGac84fJgysfJKeI5MPGuvqNBthFs+0GdiJMRmIMlhlMd+m3OFoG2Q+hZ00fNqh+DJ1NyS9BpGTd6ZQ2uuJkrae/LzbCnfznpovak+8uOWwUZrBmFg5ee654g8VkwOM5D/qvq3J5PAf/T1zUTRzKQ+rM1nCf0gqjIJ+85iIrNULJ7ro3E="
branches:
  except:
    - travis
